--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '4',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AI_Start'] = {
            ['rectangle'] = RECTANGLE( 4.5, 121.5, 51.5, 159.5 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Eng6_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 29.7823, 72.9157, 122.021 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 30.5, 72.9102, 136.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.5, 72.9219, 134.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 220.5, 72.9219, 141.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 225.5, 72.9219, 109.5 ),
                },
                ['Cam_ACURush'] = {
                    ['zoom'] = FLOAT( 133.266006 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 1.77697, 0.293077, 0 ),
                    ['position'] = VECTOR3( 82.5, 69.8814, 147.5 ),
                },
                ['1_Eng7_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 125.5, 64, 62.5 ),
                },
                ['Cam_NorthernChoke'] = {
                    ['zoom'] = FLOAT( 110.274254 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 2.26559, 0.379952, 0 ),
                    ['position'] = VECTOR3( 94.8835, 74.4343, 57.6396 ),
                },
                ['1_Eng5_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 71.5, 72.9297, 189.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 127.5, 77.9219, 13.5 ),
                },
                ['Eng5_AttackMove'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 135.5, 64.1719, 199.5 ),
                },
                ['2_Eng5_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 119.5, 64.2227, 195.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 232.5, 72.9219, 77.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 243.5, 72.9219, 243.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 83.5, 72.9297, 105.5 ),
                },
                ['Fac_2_Rally'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 119.5, 64.2305, 129.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 211.5, 72.9297, 54.5 ),
                },
                ['Fac_1_Rally'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 56.5, 71.5996, 134.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 21.5, 72.9219, 158.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 24.5, 72.9219, 140.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 229.5, 72.9219, 164.5 ),
                },
                ['1_Eng1_Hydro'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 31.7293, 72.908, 122.166 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 127.5, 64, 53.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 193.5, 70.8828, 109.5 ),
                },
                ['Eng7_AttackMove'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 142.5, 64.8438, 56.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 39.5, 72.9297, 201.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 176.5, 77.8066, 214.5 ),
                },
                ['Cam_SouthernChoke'] = {
                    ['zoom'] = FLOAT( 145.507660 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.990764, 0.457742, 0 ),
                    ['position'] = VECTOR3( 107.014, 65.706, 197.322 ),
                },
                ['AirScout_Patrol_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 233.5, 72.9219, 70.5 ),
                },
                ['ACU_Move_Enemy'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 191.5, 70.6367, 109.5 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 71.5, 77.6641, 225.5 ),
                },
                ['1_Eng3_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 27.5, 72.9219, 98.5 ),
                },
                ['2_Eng3_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 14.5, 72.9219, 20.5 ),
                },
                ['3_Eng3_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 78.5, 72.9297, 100.5 ),
                },
                ['Cam_MainRoute'] = {
                    ['zoom'] = FLOAT( 159.959061 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 2.32348, 0.36359, 0 ),
                    ['position'] = VECTOR3( 124.5, 65.343, 132.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 231.5, 72.9219, 115.5 ),
                },
                ['Cam_Stones'] = {
                    ['zoom'] = FLOAT( 77.064140 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.65139, 0.644863, 0 ),
                    ['position'] = VECTOR3( 33.4659, 72.9297, 225.265 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 16.5, 72.9219, 144.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 235.5, 72.9219, 121.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 26.5, 72.9219, 91.5 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 184.5, 77.6641, 30.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 35.5, 72.9219, 114.5 ),
                },
                ['Eng2_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 4.5, 72.9219, 214.5 ),
                },
                ['Final_Rally'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 163.5, 67.5059, 114.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 127.5, 64, 127.5 ),
                },
                ['Air_Fac_Rally'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 65.5, 72.9297, 113.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 239.5, 72.9219, 111.5 ),
                },
                ['Cam_StartPosition'] = {
                    ['zoom'] = FLOAT( 77.064140 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.68999, 0.700656, 0 ),
                    ['position'] = VECTOR3( 33.5, 72.9009, 138.5 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 152.5, 72.9102, 146.5 ),
                },
                ['Cam_StartBuildOrder'] = {
                    ['zoom'] = FLOAT( 33.316490 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.32599, 0.70509, 0 ),
                    ['position'] = VECTOR3( 25.1467, 72.9219, 140.827 ),
                },
                ['ACU_Move_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 39.5, 72.8379, 127.5 ),
                },
                ['Eng2_AttackMove'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 72.9219, 232.5 ),
                },
                ['AttackGroup1_Move_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 52.5, 73.0332, 208.5 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 178.5, 72.9297, 60.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 23.5, 72.9219, 177.5 ),
                },
                ['1_Eng2_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 23.5, 72.9219, 170.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 127.5, 77.9297, 242.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 30.5, 72.9219, 146.5 ),
                },
                ['Eng4_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 31.6609, 72.9, 124.419 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 77.5, 72.9297, 195.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 62.5, 70.8828, 146.5 ),
                },
                ['Cam_MapInfo'] = {
                    ['zoom'] = FLOAT( 526.437439 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 3.14159, 1.52143, 0 ),
                    ['position'] = VECTOR3( 129.5, 64.0201, 126.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 12.5, 72.9219, 13.5 ),
                },
                ['4_Eng3_Radar'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 93.5, 72.9297, 99.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 234.5, 72.9219, 97.5 ),
                },
                ['AirScout_Patrol_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 232.5, 72.9219, 145.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 172.5, 72.9297, 150.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 127.5, 64, 202.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 225.5, 72.9102, 119.5 ),
                },
                ['AttackGroup3_Move_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 142.5, 64.8672, 117.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 79.5, 77.8066, 41.5 ),
                },
                ['AttackGroup4_Move_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 72.5, 74.3594, 63.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 103.5, 72.9102, 109.5 ),
                },
                ['AirScout_Patrol_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 187.5, 70.168, 102.5 ),
                },
                ['Cam_ACURush_2'] = {
                    ['zoom'] = FLOAT( 100.996780 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 1.77697, 0.293077, 0 ),
                    ['position'] = VECTOR3( 209.768, 72.5608, 112.593 ),
                },
            },
        },
    },
    Chains = {
        ['AirScout_Patrol_Chain'] = {
            Markers = {
                "AirScout_Patrol_1",
                "AirScout_Patrol_2",
                "AirScout_Patrol_3",
            },
        },
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '6',
    next_group_id = '10',
    next_unit_id = '36',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Tutorial_AI'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Engineer5_Build'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['1_Eng5_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 77.500000, 72.929688, 195.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['2_Eng5_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 64.000000, 202.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['ACU'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['ACU'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 24.500000, 72.921875, 140.500000 },
                                Orientation = { 0.000000, 1.675514, 0.000000 },
                            },
                        },
                    },
                    ['ACU_Initial'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['1_Fac'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 25.500000, 72.921875, 133.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['2_Pgen'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 20.500000, 72.921875, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['4_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 30.500000, 72.910156, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['5_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 30.500000, 72.921875, 146.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['6_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 16.500000, 72.921875, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['3_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 20.500000, 72.921875, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['Engineer1_Build'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['3_Eng1_Fac'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 33.500000, 72.888672, 131.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['2_Eng1_Pgen'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 30.500000, 72.902344, 126.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['1_Eng1_Hydro'] = {
                                type = 'ueb1102',
                                orders = '',
                                platoon = '',
                                Position = { 35.500000, 72.921875, 114.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['7_Eng1_Pgen'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 28.500000, 72.921875, 118.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['10_Eng1_Pgen'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 20.500000, 72.921875, 132.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['9_Eng1_Fac'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 15.500000, 72.921875, 133.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['4_Eng1_Pgen'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 33.500000, 72.886719, 126.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['8_Eng1_Fac'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 28.500000, 72.921875, 113.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['5_Eng1_Fac'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 36.500000, 72.894531, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['6_Eng1_Fac'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 25.500000, 72.921875, 123.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Engineer2_Build'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['1_Eng2_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 23.500000, 72.921875, 177.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['Engineer3_Build'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['4_Eng3_Radar'] = {
                                type = 'ueb3101',
                                orders = '',
                                platoon = '',
                                Position = { 100.500000, 72.929688, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['1_Eng3_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 26.500000, 72.921875, 91.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['2_Eng3_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 12.500000, 72.921875, 13.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['3_Eng3_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 83.500000, 72.929688, 105.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['Engineer7_Build'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['1_Eng7_Mex'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 64.000000, 53.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Player'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Commander'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 24.500000, 72.921875, 140.500000 },
                        Orientation = { 0.000000, 1.666788, 0.000000 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
