--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '3',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AI_Start'] = {
            ['rectangle'] = RECTANGLE( 44.5, 320.5, 100.5, 370.5 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 105.5, 34.7266, 254.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 433.5, 31.6953, 166.5 ),
                },
                ['Combat Zone 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 120.665, 33.2473, 67.3385 ),
                },
                ['Fac_5_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 117.5, 34.8516, 226.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 476.5, 25.3906, 324.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 31.6016, 346.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 9.5, 25.3906, 190.5 ),
                },
                ['Mass 23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 352.5, 34.8516, 487.5 ),
                },
                ['Rally Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.659, 33.7131, 68.9595 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 435.5, 31.9277, 182.5 ),
                },
                ['Mass 33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 170.5, 25.3906, 425.5 ),
                },
                ['ACU_Move_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 34.8047, 485.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.293, 461.5 ),
                },
                ['Mass 34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 357.5, 25.4102, 97.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 470.5, 25.1016, 461.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 26.2832, 29.5 ),
                },
                ['Fac_2_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.361, 34.8143, 242.387 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 34.8047, 480.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 160.5, 25.4063, 373.5 ),
                },
                ['Rally Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 355.142, 25.3896, 141.348 ),
                },
                ['Fac_1_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 86.5, 31.6445, 331.5 ),
                },
                ['NEUTRAL_CIVILIAN'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 218.666, 25.5519, 130.206 ),
                },
                ['Mass 26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.392699, 0, 0 ),
                    ['position'] = VECTOR3( 80.5, 34.7266, 242.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 31.9668, 339.5 ),
                },
                ['Engie_2_Attack_Move_1_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 122.5, 34.7441, 268.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 398.5, 34.8262, 284.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 22.5, 25.3906, 202.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 387.362, 33.4248, 433.305 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.7682, 31.9706, 334.361 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 129.5, 34.8379, 199.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.884, 29.1037, 154.981 ),
                },
                ['Fac_4_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 55.5, 27.0195, 48.5 ),
                },
                ['Mass 30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 405.5, 34.7266, 256.5 ),
                },
                ['Combat Zone 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 394.349, 32.986, 432.645 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.5, 25.3438, 49.5 ),
                },
                ['Mass 32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 25.3906, 413.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 443.5, 31.9922, 173.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 31.9922, 339.5 ),
                },
                ['ACU_Move_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 465.5, 26.2617, 471.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 449.5, 31.9688, 183.5 ),
                },
                ['Mass 22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 170.5, 34.8047, 30.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 443.5, 31.9453, 162.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 25.3906, 322.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 30.5, 25.3906, 180.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 168.5, 34.8613, 17.5 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 394.5, 34.8613, 276.5 ),
                },
                ['Mass 28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 126.5, 34.7383, 266.5 ),
                },
                ['ARMY_9'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 243.294, 25.4314, 151.549 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.5, 25.2734, 29.5 ),
                },
                ['Fac_3_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 150.5, 25.3672, 360.5 ),
                },
                ['Mass 29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 430.5, 34.7266, 268.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 121.304, 34.8438, 233.924 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 64.5, 31.9688, 329.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.2734, 481.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.3906, 308.5 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.475, 34.8326, 232.619 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 453.5, 31.9922, 173.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 469.763, 26.5011, 481.742 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 31.9082, 349.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 396.5, 34.832, 318.5 ),
                },
                ['Engie_3_Attack_Move_1_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 370.5, 34.4844, 449.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 25.1133, 49.5 ),
                },
                ['Mass 31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 384.5, 34.7539, 245.5 ),
                },
                ['Mass 24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 342.5, 34.8438, 493.5 ),
                },
                ['Mass 35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 25.3906, 85.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 130.113, 34.8203, 217.28 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 104.712, 28.8129, 357.384 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 389.716, 34.8482, 285.853 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 158.5, 34.8438, 23.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '10',
    next_group_id = '18',
    next_unit_id = '447',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Tokyto_AI'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Buildings'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Main_Base'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['Fac_Spam'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['1_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 75.500000, 31.761719, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['4_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 69.500000, 31.968750, 326.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['2_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 85.500000, 31.400391, 343.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['3_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 83.500000, 31.335938, 351.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                        },
                                    },
                                    ['Fac7'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 61.500000, 31.953125, 324.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['ACU_Initial'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['13_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 62.500000, 31.992188, 343.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['12_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 62.500000, 31.992188, 341.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['9_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 68.500000, 31.988281, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['10_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 66.500000, 31.992188, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['11_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 64.500000, 31.992188, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['6_Mex'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 60.500000, 31.992188, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['7_Mex'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 64.500000, 31.968750, 329.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['5_Mex'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 70.500000, 31.908203, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['1_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 77.500000, 31.773438, 341.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['3_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 72.500000, 31.917969, 341.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['2_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 72.500000, 31.898438, 344.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['14_Fac'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 67.500000, 31.972656, 344.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['8_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 72.500000, 31.933594, 338.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['4_Mex'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 80.500000, 31.601563, 346.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['15_Bot_Fac'] = {
                                                type = 'ueb0101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 355.500000, 34.804688, 482.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                        },
                                    },
                                    ['E_Spam'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['13_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 54.500000, 31.992188, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['12_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 52.500000, 31.992188, 341.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['14_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 56.500000, 31.992188, 339.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['1_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 62.500000, 31.992188, 345.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['11_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 52.500000, 31.992188, 343.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['10_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 52.500000, 31.992188, 345.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['15_EStorage'] = {
                                                type = 'ueb1105',
                                                orders = '',
                                                platoon = '',
                                                Position = { 46.500000, 31.992188, 335.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['5_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 60.500000, 31.992188, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['4_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 64.500000, 31.974609, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['3_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 66.500000, 31.968750, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['2_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 68.500000, 31.945313, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['9_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 52.500000, 31.992188, 347.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['8_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 54.500000, 31.992188, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['7_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 56.500000, 31.992188, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                            ['6_Pgen'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 58.500000, 31.992188, 349.500000 },
                                                Orientation = { 0.000000, 0.000000, 0.000000 },
                                            },
                                        },
                                    },
                                },
                            },
                            ['Expansion_Top'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['2_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 105.500000, 34.726563, 254.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 80.500000, 34.726563, 242.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Top_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 83.500000, 34.820313, 237.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Top_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 75.500000, 34.835938, 239.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 126.500000, 34.738281, 266.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Expansion_Left'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['16_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 52.500000, 27.695313, 36.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['17_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 51.500000, 27.531250, 36.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 52.500000, 27.531250, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 52.500000, 27.615234, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 50.500000, 27.251953, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 51.500000, 27.349609, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_Left_PD'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 51.500000, 27.443359, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['8_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 40.500000, 26.283203, 29.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 40.500000, 25.113281, 49.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 20.500000, 25.343750, 49.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 9.500000, 25.390625, 190.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['18_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 50.500000, 27.347656, 36.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Left_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 15.500000, 25.291016, 83.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Left_Hydro'] = {
                                        type = 'ueb1102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 30.500000, 25.390625, 180.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Left_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 24.500000, 25.269531, 77.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 22.500000, 25.390625, 202.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['9_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 20.500000, 25.273438, 29.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 50.500000, 27.158203, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Expansion_Bot'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['8_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.808594, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 170.500000, 25.390625, 425.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.828125, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.857422, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.847656, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_Bot_PD'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.822266, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_Bot_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 345.500000, 34.832031, 487.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 153.500000, 25.390625, 413.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.808594, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.808594, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.804688, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 352.500000, 34.851563, 487.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['9_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.818359, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 340.500000, 34.804688, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 342.500000, 34.843750, 493.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                        },
                    },
                    ['ACU'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['ACU'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 70.500000, 31.966797, 339.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Player'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Player_ACU'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Commander'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 443.500000, 31.992188, 173.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
