--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '3',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AI_Start'] = {
            ['rectangle'] = RECTANGLE( 44.5, 320.5, 100.5, 370.5 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Engie_2_Attack_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 155.5, 33.0215, 271.5 ),
                },
                ['Engineer_5_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 69.5, 31.9531, 345.5 ),
                },
                ['Rally Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 77.5, 31.8945, 330.5 ),
                },
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 105.5, 34.7266, 254.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 433.5, 31.6953, 166.5 ),
                },
                ['Combat Zone 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 120.665, 33.2473, 67.3385 ),
                },
                ['Cam_TwoMexHydro'] = {
                    ['zoom'] = FLOAT( 85.109352 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.07614, 0.619248, 0 ),
                    ['position'] = VECTOR3( 29.5, 25.2562, 186.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 476.5, 25.3906, 324.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 453.5, 31.9922, 173.5 ),
                },
                ['Cam_PlateauEast'] = {
                    ['zoom'] = FLOAT( 263.979309 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 1.82605, 0.342164, 0 ),
                    ['position'] = VECTOR3( 295.5, 26.8389, 378.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 9.5, 25.3906, 190.5 ),
                },
                ['Mass 23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 352.5, 34.8516, 487.5 ),
                },
                ['Cam_Pond'] = {
                    ['zoom'] = FLOAT( 127.178307 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.543226, 0.579977, 0 ),
                    ['position'] = VECTOR3( 41.5, 24.5457, 85.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 435.5, 31.9277, 182.5 ),
                },
                ['Mass 33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 170.5, 25.3906, 425.5 ),
                },
                ['ACU_Move_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 34.8047, 485.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.293, 461.5 ),
                },
                ['Mass 34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 357.5, 25.4102, 97.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 470.5, 25.1016, 461.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 26.2832, 29.5 ),
                },
                ['Fac_2_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.361, 34.8143, 242.387 ),
                },
                ['Engie_3_Attack_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 122.5, 34.7441, 268.5 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 34.8047, 480.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 160.5, 25.4063, 373.5 ),
                },
                ['Rally Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 355.142, 25.3896, 141.348 ),
                },
                ['Fac_1_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 86.5, 31.6445, 331.5 ),
                },
                ['NEUTRAL_CIVILIAN'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 218.666, 25.5519, 130.206 ),
                },
                ['Mass 26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.392699, 0, 0 ),
                    ['position'] = VECTOR3( 80.5, 34.7266, 242.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 31.9668, 339.5 ),
                },
                ['15_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 165.5, 34.8164, 24.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 398.5, 34.8262, 284.5 ),
                },
                ['Cam_Choke'] = {
                    ['zoom'] = FLOAT( 127.178307 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 1.94714, 0.566888, 0 ),
                    ['position'] = VECTOR3( 247.5, 26.0225, 247.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 22.5, 25.3906, 202.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 387.362, 33.4248, 433.305 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.7682, 31.9706, 334.361 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 129.5, 34.8379, 199.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.884, 29.1037, 154.981 ),
                },
                ['Cam_ThreeMexTop'] = {
                    ['zoom'] = FLOAT( 88.274414 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 2.87653, 1.04467, 0 ),
                    ['position'] = VECTOR3( 164.5, 34.252, 32.5 ),
                },
                ['Fac_4_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 55.5, 27.0195, 48.5 ),
                },
                ['Cam_MapInfo'] = {
                    ['zoom'] = FLOAT( 1137.320679 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 3.14159, 1.54071, 0 ),
                    ['position'] = VECTOR3( 284.5, 29.7623, 236.5 ),
                },
                ['Mass 30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 405.5, 34.7266, 256.5 ),
                },
                ['Combat Zone 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 394.349, 32.986, 432.645 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.5, 25.3438, 49.5 ),
                },
                ['Mass 32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 25.3906, 413.5 ),
                },
                ['Cam_ReclaimNearBase'] = {
                    ['zoom'] = FLOAT( 70.906837 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.6278, 0.612703, 0 ),
                    ['position'] = VECTOR3( 150.5, 25.8545, 296.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 443.5, 31.9922, 173.5 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 158.5, 34.8438, 23.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 31.9922, 339.5 ),
                },
                ['Rally Point 08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 89.5, 32.0645, 301.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 396.5, 34.832, 318.5 ),
                },
                ['Cam_TwoMexSide'] = {
                    ['zoom'] = FLOAT( 70.906837 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.117818, 0.635609, 0 ),
                    ['position'] = VECTOR3( 161.5, 25.4645, 411.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 449.5, 31.9688, 183.5 ),
                },
                ['Attack_Group_1_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 186.5, 25.3906, 282.5 ),
                },
                ['Mass 22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 170.5, 34.8047, 30.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 443.5, 31.9453, 162.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 25.3906, 322.5 ),
                },
                ['Cam_BO_Start'] = {
                    ['zoom'] = FLOAT( 72.658165 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.14159, 1.07845, 0 ),
                    ['position'] = VECTOR3( 70.4473, 31.9618, 340.871 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.475, 34.8326, 232.619 ),
                },
                ['1_Left_Mex'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 66.2657, 31.9922, 335.524 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 30.5, 25.3906, 180.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 168.5, 34.8613, 17.5 ),
                },
                ['14_Fac'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 135.5, 34.5898, 261.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.5, 25.2734, 29.5 ),
                },
                ['ARMY_9'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 243.294, 25.4314, 151.549 ),
                },
                ['Cam_ThreeMexHillside'] = {
                    ['zoom'] = FLOAT( 85.109352 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.886837, 0.687969, 0 ),
                    ['position'] = VECTOR3( 104.5, 35.9514, 252.5 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 394.5, 34.8613, 276.5 ),
                },
                ['Mass 31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 384.5, 34.7539, 245.5 ),
                },
                ['Mass 29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 430.5, 34.7266, 268.5 ),
                },
                ['Rally Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 128.659, 33.7131, 68.9595 ),
                },
                ['ACU_Move_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 465.5, 26.2617, 471.5 ),
                },
                ['Engineer_2_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 150.5, 25.6504, 313.5 ),
                },
                ['Cam_PlateauWest'] = {
                    ['zoom'] = FLOAT( 183.227753 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.97797, 0.416353, 0 ),
                    ['position'] = VECTOR3( 158.5, 28.4805, 188.5 ),
                },
                ['Fac_5_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 117.5, 34.8516, 226.5 ),
                },
                ['Fac_3_Rally'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 150.5, 25.3672, 360.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 121.304, 34.8438, 233.924 ),
                },
                ['Mass 24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 342.5, 34.8438, 493.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.2734, 481.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 490.5, 25.3906, 308.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 31.6016, 346.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 31.9082, 349.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 469.763, 26.5011, 481.742 ),
                },
                ['Cam_FourMexCorner'] = {
                    ['zoom'] = FLOAT( 88.274414 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.48709, 0.881046, 0 ),
                    ['position'] = VECTOR3( 36.5, 25.6318, 37.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 64.5, 31.9688, 329.5 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 104.712, 28.8129, 357.384 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 25.1133, 49.5 ),
                },
                ['Rally Point 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 187.5, 25.4063, 290.5 ),
                },
                ['Mass 28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 126.5, 34.7383, 266.5 ),
                },
                ['Mass 35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 340.5, 25.3906, 85.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 130.113, 34.8203, 217.28 ),
                },
                ['Cam_StartPosition'] = {
                    ['zoom'] = FLOAT( 73.543808 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -2.72925, 0.769783, 0 ),
                    ['position'] = VECTOR3( 78.5, 31.4569, 338.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 389.716, 34.8482, 285.853 ),
                },
                ['Attack_Group_3_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 191.5, 24.8965, 408.5 ),
                },
                ['Engineer_6_Move'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 138.5, 34.1875, 265.5 ),
                },
                ['Engineer_6_AttackMove'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 75.5, 35.1543, 236.5 ),
                },
                ['AirScout_Patrol_00'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 25.3906, 228.5 ),
                },
                ['AirScout_Patrol_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 492.5, 25.3906, 303.5 ),
                },
                ['AirScout_Patrol_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 383.5, 25.9746, 124.5 ),
                },
                ['Hillside_Factory_Patrol0'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 115.494, 34.8047, 242.733 ),
                },
                ['Hillside_Factory_Patrol1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 84.5, 34.8574, 240.5 ),
                },
                ['Hillside_Factory_Patrol2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 132.5, 35.1289, 267.5 ),
                },
            },
        },
    },
    Chains = {
        ['AirScout_Patrol_Chain'] = {
            Markers = {
                "AirScout_Patrol_00",
                "AirScout_Patrol_01",
                "AirScout_Patrol_02",
            },
        },
        ['Hillside_Factory_Patrol_Chain'] = {
            Markers = {
                "Hillside_Factory_Patrol0",
                "Hillside_Factory_Patrol1",
                "Hillside_Factory_Patrol2",
            },
        },
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '10',
    next_group_id = '26',
    next_unit_id = '504',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Tutorial_AI'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Buildings'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['ACU_Initial'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['18_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 165.500000, 34.804688, 30.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 129.500000, 34.742188, 261.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['17_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 158.500000, 34.800781, 23.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['9_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 75.500000, 31.791016, 346.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 170.500000, 34.804688, 30.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['16_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 168.500000, 34.839844, 17.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 66.500000, 31.978516, 345.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 80.500000, 31.601563, 346.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 70.500000, 31.908203, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 64.500000, 31.974609, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_Fac'] = {
                                        type = 'ueb0102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 61.500000, 31.992188, 344.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 61.500000, 31.984375, 334.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 62.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 58.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 66.500000, 31.968750, 347.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['8_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 66.500000, 31.984375, 343.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 66.500000, 31.992188, 341.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 64.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Expansion_Top'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['2_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 105.500000, 34.726563, 254.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 80.500000, 34.726563, 242.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Top_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 126.500000, 34.738281, 266.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Expansion_Bot'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['8_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.808594, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 170.500000, 25.390625, 425.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.828125, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.857422, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 153.500000, 25.390625, 413.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_Bot_PD'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.822266, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['9_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.818359, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Bot_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 161.500000, 25.388672, 426.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.808594, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 348.500000, 34.808594, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 346.500000, 34.804688, 479.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 352.500000, 34.851563, 487.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 340.500000, 34.804688, 480.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_Bot_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 347.500000, 34.847656, 481.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Bot_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 342.500000, 34.843750, 493.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Fac_Spam'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['4_FacSpam_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 69.500000, 31.976563, 332.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_FacSpam_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 67.500000, 31.953125, 324.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_FacSpam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 70.500000, 31.972656, 337.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_FacSpam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 68.500000, 31.992188, 337.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_FacSpam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 66.500000, 31.992188, 337.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_FacSpam_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 59.500000, 31.960938, 326.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_FacSpam_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 80.500000, 31.769531, 317.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['Expansion_Left'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['9_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 20.500000, 25.273438, 29.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 42.500000, 25.783203, 39.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['16_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 43.500000, 25.919922, 39.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 40.500000, 26.283203, 29.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 40.500000, 25.113281, 49.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 60.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 64.500000, 31.968750, 329.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_Left_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 33.500000, 25.230469, 39.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_Left_Radar'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 34.500000, 25.390625, 182.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['18_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 26.140625, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['19_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 26.230469, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['3_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 22.500000, 25.390625, 202.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 9.500000, 25.390625, 190.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_Left_PD'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 43.500000, 26.003906, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['8_Left_Mex'] = {
                                        type = 'ueb1103',
                                        orders = '',
                                        platoon = '',
                                        Position = { 20.500000, 25.343750, 49.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['21_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 42.500000, 25.953125, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['20_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 43.500000, 26.085938, 37.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_Left_Hydro'] = {
                                        type = 'ueb1102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 30.500000, 25.390625, 180.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 42.500000, 25.871094, 38.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['17_Left_Wall'] = {
                                        type = 'ueb5101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 26.056641, 39.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_Left_Fac'] = {
                                        type = 'ueb0101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 24.500000, 25.269531, 77.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                            ['E_Spam'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['3_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 58.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['11_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 46.500000, 31.992188, 341.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['10_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 48.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['4_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 56.500000, 31.992188, 347.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['2_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 60.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['5_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 56.500000, 31.992188, 345.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['17_EStorage'] = {
                                        type = 'ueb1105',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 31.976563, 356.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['6_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 56.500000, 31.992188, 343.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['1_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 62.500000, 31.988281, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['8_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 54.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['7_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 56.500000, 31.992188, 341.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['9_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 51.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['12_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 46.500000, 31.992188, 344.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['13_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 46.500000, 31.992188, 347.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['14_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 48.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['15_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 51.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['16_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 54.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['18_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['19_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 41.500000, 31.992188, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['20_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 38.500000, 31.974609, 349.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['21_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 36.500000, 31.970703, 347.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['22_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 36.500000, 31.988281, 344.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['23_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 36.500000, 31.992188, 341.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['24_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 38.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['25_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 41.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                    ['26_E_Spam_Pgen'] = {
                                        type = 'ueb1101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 44.500000, 31.992188, 339.500000 },
                                        Orientation = { 0.000000, 0.000000, 0.000000 },
                                    },
                                },
                            },
                        },
                    },
                    ['ACU'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['ACU'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 70.500000, 31.966797, 339.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Player'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['Player_ACU'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Commander'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 443.500000, 31.992188, 173.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
